C_F		= -Wall -Wextra -Werror -std=c++98
C++		= c++
aumane		= main.cpp
OBJ		= $(aumane:.cpp=.o)
NAME	= Sed_is_for_losers


all: $(NAME)

$(NAME): $(OBJ)
	$(C++) $(C_F) $(OBJ) -o $(NAME)

%.o: %.cpp
	$(C++) $(C_F) -c $< -o $@

clean: 
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: clean all
